// French for the whole site. js/i18n.js applies it to what is on screen.
//
//   WORDS   a text exactly as the pages write it in English -> French
//   TERMS   game stats, in lower case. Used alone ("Weapon Damage") and after a number
//           ("15% Weapon Damage", "+1 Skill Tier"), whatever the capitals
//   RULES   texts with a number or a name inside them
//   SCOPED  a word that needs another translation in one particular place
//
// Stat and mode names follow the French version of the game. Item, talent, skill and mission
// names and talent descriptions are left as the community sheet gives them.
//
// To add a text: copy the English exactly as it appears in the page's code into WORDS.

export const WORDS = {
  // ---- shared header and footer ----
  'Division 2 Build Planner': 'Planificateur de builds Division 2',
  'Division 2 Seasonal Calendar': 'Calendrier saisonnier Division 2',
  'Division 2 Escalation Rotation and Target Loot': 'Rotation d’Escalade et butin ciblé Division 2',
  'Build Planner': 'Planificateur de builds',
  'Build planner': 'Planificateur de builds',
  'Seasonal Calendar': 'Calendrier saisonnier',
  'Seasonal calendar': 'Calendrier saisonnier',
  'Escalation Loot': 'Butin d’Escalade',
  'Escalation loot': 'Butin d’Escalade',
  'Tools': 'Outils',
  'Language': 'Langue',
  'Synchronizing loadout data': 'Synchronisation des données d’équipement',
  'Loading game data…': 'Chargement des données du jeu…',
  'Build actions': 'Actions du build',
  'Copy link': 'Copier le lien',
  'Copy as text': 'Copier en texte',
  'Saved builds': 'Builds enregistrés',
  'New build': 'Nouveau build',
  'Animations: on': 'Animations : activées',
  'Animations: off': 'Animations : désactivées',
  'Loadout': 'Équipement',
  'Build statistics': 'Statistiques du build',
  'Edit slot': 'Modifier l’emplacement',
  'Fan-made tool, not affiliated with Ubisoft. Numbers are estimates. Game data from the community': 'Outil créé par un fan, non affilié à Ubisoft. Les chiffres sont des estimations. Données du jeu issues de la feuille communautaire',
  'Fan-made reference, not affiliated with Ubisoft. Dates may change.': 'Référence créée par un fan, non affiliée à Ubisoft. Les dates peuvent changer.',
  'Fan-made reference, not affiliated with Ubisoft. Rotation data from': 'Référence créée par un fan, non affiliée à Ubisoft. Données de rotation fournies par',
  'Plan and share builds for The Division 2 with every weapon, gear piece and talent, kept in sync with the community gear spreadsheet.': 'Créez et partagez des builds pour The Division 2 avec chaque arme, pièce d’équipement et talent, synchronisés avec la feuille communautaire.',
  'What is live, what is next and what has ended in The Division 2: seasons, events and countdowns.': 'Ce qui est en cours, ce qui arrive et ce qui est terminé dans The Division 2 : saisons, événements et comptes à rebours.',
  "This week's Division 2 Escalation missions, today's target loot and the Requisition vendor caches.": 'Les missions d’Escalade de la semaine dans The Division 2, le butin ciblé du jour et les caisses du vendeur de réquisition.',

  // ---- words used all over ----
  'None': 'Aucun',
  'All': 'Tout',
  'Close': 'Fermer',
  'Remove': 'Retirer',
  'Back': 'Retour',
  'Done': 'Terminé',
  'Change': 'Changer',
  'Clear': 'Effacer',
  'Empty': 'Vide',
  'Load': 'Charger',
  'Delete': 'Supprimer',
  'Search': 'Rechercher',
  'Choose': 'Choisir',
  'Configure': 'Configurer',
  'Custom': 'Sur mesure',
  'Weapon': 'Arme',
  'Weapons': 'Armes',
  'Gear': 'Équipement',
  'Skill': 'Compétence',
  'Skills': 'Compétences',
  'Attributes': 'Attributs',
  'Core': 'Attribut principal',
  'Brand': 'Marque',
  'Brands': 'Marques',
  'Gear set': 'Ensemble d’équipement',
  'Gear sets': 'Ensembles d’équipement',
  'Brand set': 'Ensemble de marque',
  'High-end': 'Haut de gamme',
  'Named': 'Nommé',
  'Exotic': 'Exotique',
  'Specialization': 'Spécialisation',
  'Augment': 'Augmentation',
  'Augments': 'Augmentations',
  'Offense': 'Attaque',
  'Defense': 'Défense',
  'Handling': 'Maniement',
  'Other': 'Autres',
  'Offensive': 'Offensif',
  'Defensive': 'Défensif',
  'in combat': 'en combat',
  'stat sheet': 'fiche de stats',

  // slots
  'Primary': 'Principale',
  'Secondary': 'Secondaire',
  'Sidearm': 'Arme de poing',
  'Primary weapon': 'Arme principale',
  'Secondary weapon': 'Arme secondaire',
  'Sidearm weapon': 'Arme de poing',
  'Mask': 'Masque', 'mask': 'masque',
  'Backpack': 'Sac à dos', 'backpack': 'sac à dos',
  'Chest': 'Gilet', 'chest': 'gilet',
  'Gloves': 'Gants', 'gloves': 'gants',
  'Holster': 'Holster', 'holster': 'holster',
  'Kneepads': 'Genouillères', 'kneepads': 'genouillères',
  'Optic': 'Optique',
  'Muzzle': 'Bouche',
  'Underbarrel': 'Sous-canon',

  // weapon classes
  'Assault Rifle': 'Fusil d’assaut',
  'LMG': 'Fusil-mitrailleur',
  'SMG': 'Pistolet-mitrailleur',
  'Shotgun': 'Fusil à pompe',
  'Rifle': 'Fusil',
  'Marksman Rifle': 'Fusil de précision',
  'Pistol': 'Pistolet',

  // specializations (data/specializations.csv)
  'Sharpshooter': 'Tireur d’élite',
  'Survivalist': 'Survivaliste',
  'Technician': 'Technicien',
  'Gunner': 'Mitrailleur',
  'Demolitionist': 'Démolisseur',
  'Firewall': 'Pare-feu',
  '+15% headshot damage with rifles and marksman rifles and +15% stability.': '+15% de dégâts de tir à la tête avec les fusils et les fusils de précision, et +15% de stabilité.',
  '+10% protection from elites and stronger outgoing healing.': '+10% de protection contre les élites et des soins prodigués renforcés.',
  '+1 skill tier and +10% skill damage.': '+1 rang de compétence et +10% de dégâts de compétence.',
  'Kills grant 10% armor.': 'Les éliminations octroient 10% de protection.',
  '+10% explosive damage.': '+10% de dégâts explosifs.',
  '+20% burn duration and +30% health on kill.': '+20% de durée de brûlure et +30% de santé par élimination.',

  // ---- build planner: board ----
  'Choose a weapon': 'Choisir une arme',
  'Choose gear': 'Choisir un équipement',
  'Choose a skill': 'Choisir une compétence',
  'SHD Watch': 'Montre SHD',
  'All maxed': 'Tout au max',
  'Not set': 'Non réglée',
  'Your SHD level': 'Votre niveau SHD',
  'optional: checks you have the points (one per category every 5 levels)': 'facultatif : vérifie que vous avez les points (un par catégorie tous les 5 niveaux)',
  'SHD level': 'Niveau SHD',
  'Max everything': 'Tout au maximum',
  'Season modifiers and other bonuses': 'Modificateurs de saison et autres bonus',
  "Seasonal modifiers, event buffs and similar bonuses are not part of your gear, so the planner cannot know them. If the game's Stats page shows more than the planner, add the difference here.": 'Les modificateurs de saison, les bonus d’événement et autres bonus similaires ne font pas partie de votre équipement : le planificateur ne peut donc pas les connaître. Si la page Stats du jeu affiche plus que le planificateur, ajoutez la différence ici.',
  'Bonus stat': 'Stat du bonus',
  'Choose a stat': 'Choisir une stat',
  'Bonus value': 'Valeur du bonus',
  'Remove bonus': 'Retirer le bonus',
  'Add a bonus': 'Ajouter un bonus',

  // ---- build planner: stats column ----
  'No weapon': 'Aucune arme',
  'DMG': 'DÉG',
  'RPM': 'CPM',
  'MAG': 'CHG',
  'Rate of fire': 'Cadence de tir',
  'Magazine': 'Chargeur',
  'Skill tier': 'Rang de compétence',
  'Weapon damage': 'Dégâts d’arme',
  'Stat sheet': 'Fiche de stats',
  'In combat': 'En combat',
  'Talents, set bonuses and stacks are counted the way the Talents and bonuses panel is set.': 'Les talents, bonus d’ensemble et cumuls sont pris en compte selon les réglages du panneau Talents et bonus.',
  'Matches the Stats page in your inventory: gear, mods, watch and always-on bonuses only. Talents that need a kill, stacks or a status effect are left out.': 'Correspond à la page Stats de votre inventaire : équipement, mods, montre et bonus permanents uniquement. Les talents qui nécessitent une élimination, des cumuls ou un effet d’état sont exclus.',
  'No weapon in this slot. The totals below show your gear on its own.': 'Aucune arme dans cet emplacement. Les totaux ci-dessous montrent votre équipement seul.',
  'Sustained DPS': 'DPS soutenu',
  'sustained DPS': 'DPS soutenu',
  'Burst DPS': 'DPS en rafale',
  'Listed weapon damage': 'Dégâts d’arme affichés',
  'All weapon damage bonus': 'Bonus de dégâts toutes armes',
  'Body shot': 'Tir au corps',
  'Critical hit': 'Coup critique',
  'Headshot': 'Tir à la tête',
  'Critical headshot': 'Tir à la tête critique',
  'Average bullet': 'Balle moyenne',
  'Reload': 'Rechargement',
  'Crit chance': 'Chances de critique',
  'Crit damage': 'Dégâts critiques',
  'Headshot damage': 'Dégâts de tir à la tête',
  'Total weapon damage': 'Dégâts d’arme totaux',
  'Amplified': 'Amplifié',
  'Damage to armor': 'Dégâts à la protection',
  'Damage to health': 'Dégâts à la santé',
  'No gear yet.': 'Aucun équipement pour l’instant.',
  'Cores and sets': 'Attributs principaux et ensembles',
  'Talents and bonuses': 'Talents et bonus',
  'Show in combat': 'Afficher en combat',
  'Crit chance (capped)': 'Chances de critique (plafonnées)',
  'Crit damage (total)': 'Dégâts critiques (total)',
  'Total armor': 'Protection totale',
  'Total health': 'Santé totale',
  'Bonus health': 'Santé bonus',
  'Armor + health': 'Protection + santé',
  'Same, against elites': 'Idem, contre les élites',
  'Armor from cores': 'Protection des attributs principaux',
  'Total armor bonus': 'Bonus de protection totale',
  'Health from attributes': 'Santé des attributs',
  'Health bonus': 'Bonus de santé',
  'Accuracy bonus': 'Bonus de précision',
  'Stability bonus': 'Bonus de stabilité',
  'Reload speed bonus': 'Bonus de vitesse de rechargement',
  'Total damage over time for each weapon. Flat stretches are reloads.': 'Dégâts totaux dans le temps pour chaque arme. Les paliers correspondent aux rechargements.',
  'Flat stretches are reloads. Uses your crit chance and the headshot chance below.': 'Les paliers correspondent aux rechargements. Utilise vos chances de critique et la probabilité de tir à la tête ci-dessous.',
  'Time to kill': 'Temps pour tuer',
  'Headshot chance %': 'Probabilité de tir à la tête %',
  'Headshot chance': 'Probabilité de tir à la tête',
  'Target preset': 'Cible prédéfinie',
  'Target armor': 'Protection de la cible',
  'Target health': 'Santé de la cible',
  'Target is out of cover': 'La cible est hors abri',
  'Bullets': 'Balles',
  'Time': 'Temps',
  'Reloads': 'Rechargements',
  'Add a weapon to see time to kill.': 'Ajoutez une arme pour voir le temps pour tuer.',
  'Example: armored enemy': 'Exemple : ennemi avec protection',
  'Example: heavily armored enemy': 'Exemple : ennemi lourdement protégé',
  'Example: unarmored enemy': 'Exemple : ennemi sans protection',
  'Loadout check': 'Vérification de l’équipement',
  'No problems found: the loadout is complete and legal.': 'Aucun problème : l’équipement est complet et valide.',
  'What to improve next': 'Quoi améliorer ensuite',
  '+15% weapon damage (one red core)': '+15% de dégâts d’arme (un attribut rouge)',
  '+6% crit chance': '+6% de chances de critique',
  '+12% crit damage': '+12% de dégâts critiques',
  '+10% headshot damage': '+10% de dégâts de tir à la tête',
  '+5% rate of fire': '+5% de cadence de tir',
  '+10% reload speed': '+10% de vitesse de rechargement',
  '+10% amplified damage': '+10% de dégâts amplifiés',
  'Compare builds': 'Comparer des builds',
  'Saved build to compare with': 'Build enregistré à comparer',
  'Choose a saved build': 'Choisir un build enregistré',
  'Save a build first (Saved builds, top of the page) to compare against it.': 'Enregistrez d’abord un build (Builds enregistrés, en haut de la page) pour le comparer.',
  'Bullet damage': 'Dégâts par balle',
  'Crit chance %': 'Chances de critique %',
  'Crit damage %': 'Dégâts critiques %',
  'This build': 'Ce build',
  'Difference': 'Différence',
  'Division 2 build': 'Build Division 2',

  // ---- build planner: editor ----
  'Search by name, brand or talent': 'Rechercher par nom, marque ou talent',
  'Nothing matches.': 'Aucun résultat.',
  'Exotic items cannot be Prototype.': 'Les objets exotiques ne peuvent pas être Prototype.',
  'Prototype item': 'Objet Prototype',
  'Attributes can roll up to 1.5 times the normal maximum.': 'Les attributs peuvent atteindre jusqu’à 1,5 fois le maximum normal.',
  'The attribute boxes below now go up to the Prototype maximum and start there. In the game only one attribute is guaranteed at the new maximum, so lower the others to match your item.': 'Les champs d’attributs ci-dessous montent désormais jusqu’au maximum Prototype et y sont réglés par défaut. En jeu, un seul attribut est garanti au nouveau maximum : baissez les autres pour correspondre à votre objet.',
  'No augment': 'Aucune augmentation',
  'Augment level (1 to 10)': 'Niveau d’augmentation (1 à 10)',
  'Augment level': 'Niveau d’augmentation',
  'Augment value': 'Valeur de l’augmentation',
  'Value shown in your game': 'Valeur affichée dans votre jeu',
  "the game's numbers are not published": 'les valeurs du jeu ne sont pas publiées',
  'Counted in average bullet damage, DPS and time to kill.': 'Prise en compte dans les dégâts moyens par balle, le DPS et le temps pour tuer.',
  'Counted in total health.': 'Prise en compte dans la santé totale.',
  'Listed in the Augments panel. It does not change the damage numbers.': 'Affichée dans le panneau Augmentations. Elle ne modifie pas les chiffres de dégâts.',
  'Described only. Not counted in the numbers.': 'Description seule. Non pris en compte dans les chiffres.',
  "The sheet text no longer matches this talent's formula, so it is not counted.": 'Le texte de la feuille ne correspond plus à la formule de ce talent : il n’est donc pas pris en compte.',
  'Does not apply to this weapon.': 'Ne s’applique pas à cette arme.',
  'Needs a condition, so it is left off the stat sheet. Switch to': 'Nécessite une condition : il est donc absent de la fiche de stats. Passez sur',
  'to count it.': 'pour le prendre en compte.',
  'as one piece of every brand and gear set you wear': 'comme une pièce de chaque marque et ensemble d’équipement que vous portez',
  'Stacks': 'Cumuls',
  'Count it': 'Prendre en compte',
  'The sheet reworded this talent. Using the last verified numbers.': 'La feuille a reformulé ce talent. Les derniers chiffres vérifiés sont utilisés.',
  'Choose an attribute': 'Choisir un attribut',
  'Core value': 'Valeur de l’attribut principal',
  'Class attribute value': 'Valeur de l’attribut de catégorie',
  'Third attribute': 'Troisième attribut',
  'Attribute value': 'Valeur de l’attribut',
  'No talent': 'Aucun talent',
  'no bonus': 'aucun bonus',
  'Fits this weapon': 'Compatible avec cette arme',
  'Other mods': 'Autres mods',
  'This weapon has no mod slots.': 'Cette arme n’a aucun emplacement de mod.',
  'No mods.': 'Aucun mod.',
  'Expertise grade': 'Grade d’expertise',
  'fixed': 'fixe',
  'No attributes on this piece.': 'Aucun attribut sur cette pièce.',
  'Gear mod': 'Mod d’équipement',
  'Gear mods': 'Mods d’équipement',
  'Per skill tier': 'Par rang de compétence',
  'This browser': 'Ce navigateur',
  'Name this build': 'Nommer ce build',
  'Build name': 'Nom du build',
  'Save current': 'Enregistrer l’actuel',
  'Nothing saved yet. Saved builds stay in this browser; use Copy link to share one.': 'Rien d’enregistré pour l’instant. Les builds enregistrés restent dans ce navigateur ; utilisez Copier le lien pour en partager un.',

  // weapon mod rails
  'Optics': 'Optiques',
  'Ammunition Belt Slot': 'Emplacement de bande de munitions',
  'Gadget Slot': 'Emplacement de gadget',
  'Integrated Magazine Slot': 'Emplacement de chargeur intégré',
  'Iron Sights Slot': 'Emplacement de viseur mécanique',
  'Long Underbarrel Rail': 'Rail sous-canon long',
  'Long/Short Optics Rail': 'Rail d’optique long/court',
  'Long/Short Underbarrel Rail': 'Rail sous-canon long/court',
  'Long/Short Underbarrel Rail/ Side slot': 'Rail sous-canon long/court / emplacement latéral',
  'Long/Short/Micro Optics Rail': 'Rail d’optique long/court/micro',
  'Marksman 7.62 Magazine Slot': 'Emplacement de chargeur 7.62 de précision',
  'Pistol Magazine Slot': 'Emplacement de chargeur de pistolet',
  'Revolver Drum Slot': 'Emplacement de barillet',
  'Short/Micro Optics Rail': 'Rail d’optique court/micro',
  'Tubular Magazine Slot': 'Emplacement de chargeur tubulaire',

  // augments (data/augments.csv)
  'Chance to gain temporary damage immunity.': 'Chance d’obtenir une immunité temporaire aux dégâts.',
  'Chance for a bullet to deal its damage a second time.': 'Chance qu’une balle inflige ses dégâts une seconde fois.',
  'Increases grenade radius and damage.': 'Augmente le rayon et les dégâts des grenades.',
  'Chance for bullet hits to apply a random status effect.': 'Chance que les tirs appliquent un effet d’état aléatoire.',
  'Extends the duration of status effects you apply.': 'Prolonge la durée des effets d’état que vous appliquez.',
  'Gain health equal to a percentage of your total armor.': 'Octroie de la santé équivalant à un pourcentage de votre protection totale.',
  'Skills heal you for a portion of the damage they deal.': 'Les compétences vous soignent d’une partie des dégâts qu’elles infligent.',
  'Chance to refill part of the magazine while firing.': 'Chance de recharger une partie du chargeur pendant le tir.',
  'Hits reduce your skill cooldowns.': 'Les tirs réduisent les temps de recharge de vos compétences.',

  // ---- build planner: messages ----
  'Live data': 'Données en direct',
  'Syncing': 'Synchronisation',
  'Offline copy': 'Copie hors ligne',
  'No data': 'Aucune donnée',
  'Showing the copy bundled with the site.': 'Affichage de la copie fournie avec le site.',
  'Read from the community sheet just now.': 'Lu à l’instant depuis la feuille communautaire.',
  'The community sheet could not be reached. Showing the copy bundled with the site.': 'La feuille communautaire est injoignable. Affichage de la copie fournie avec le site.',
  'That build link could not be read.': 'Ce lien de build est illisible.',
  'This browser is blocking saved builds. Use the link instead.': 'Ce navigateur bloque l’enregistrement des builds. Utilisez plutôt le lien.',
  'Started a new build.': 'Nouveau build commencé.',
  'Animations on.': 'Animations activées.',
  'Animations off.': 'Animations désactivées.',
  'Build link copied.': 'Lien du build copié.',
  'Copy the address from the address bar to share this build.': 'Copiez l’adresse dans la barre d’adresse pour partager ce build.',
  'Build copied as text.': 'Build copié en texte.',
  'Copying was blocked by the browser.': 'La copie a été bloquée par le navigateur.',
  'Type a name for the build first.': 'Saisissez d’abord un nom pour le build.',
  'Animations are off because your system has animation effects turned off. Use the Animations button to switch them on.': 'Les animations sont désactivées car les effets d’animation de votre système sont coupés. Utilisez le bouton Animations pour les activer.',
  'The game data could not be loaded': 'Impossible de charger les données du jeu',
  'If you opened index.html by double-clicking it, run it through a web server instead (see README).': 'Si vous avez ouvert index.html par un double-clic, passez plutôt par un serveur web (voir le README).',

  // ---- "Assumes" lines of the talents (data/talent_effects.csv) ----
  'A stack available for every round': 'Un cumul disponible pour chaque balle',
  'After a cover to cover move': 'Après un déplacement d’abri en abri',
  'After a critical hit kill': 'Après une élimination par coup critique',
  'After a headshot': 'Après un tir à la tête',
  'After a kill': 'Après une élimination',
  'After a kill at the matching range': 'Après une élimination à la bonne distance',
  'After a kill within 7 m': 'Après une élimination à moins de 7 m',
  'After a skill kill': 'Après une élimination avec une compétence',
  'After a weapon swap': 'Après un changement d’arme',
  'After applying a status effect': 'Après avoir appliqué un effet d’état',
  'After damaging an enemy with a skill': 'Après avoir blessé un ennemi avec une compétence',
  'After destroying a weakpoint': 'Après avoir détruit un point faible',
  'After emptying your signature weapon': 'Après avoir vidé votre arme emblématique',
  'After hitting an enemy with no armor': 'Après avoir touché un ennemi sans protection',
  'After interacting with your skill': 'Après avoir interagi avec votre compétence',
  'After killing an enemy with a status effect': 'Après avoir éliminé un ennemi sous effet d’état',
  'After reloading from empty': 'Après un rechargement à vide',
  'After reloading with stacks': 'Après un rechargement avec des cumuls',
  'After shooting an enemy': 'Après avoir tiré sur un ennemi',
  'After staying in cover': 'Après être resté à l’abri',
  'After suppressing an enemy': 'Après avoir mis un ennemi sous suppression',
  'After swapping to this weapon': 'Après être passé à cette arme',
  'After swapping weapons and at the right range': 'Après un changement d’arme et à la bonne distance',
  'After the consecutive kills': 'Après les éliminations consécutives',
  'After the reloads that trigger it': 'Après les rechargements qui le déclenchent',
  'After using or cancelling a skill': 'Après avoir utilisé ou annulé une compétence',
  'After your shield breaks': 'Après la destruction de votre bouclier',
  'All 8 pellets hit': 'Les 8 plombs touchent',
  'Applies to the next headshot': 'S’applique au prochain tir à la tête',
  'At full armor': 'Avec la protection au maximum',
  'Averaged over a full health bar': 'Moyenne sur une barre de santé complète',
  'Averaged over a magazine': 'Moyenne sur un chargeur',
  'Averaged over the moon cycle (5% to 25%)': 'Moyenne sur le cycle lunaire (5% à 25%)',
  'Body shot stacks on the target': 'Cumuls de tirs au corps sur la cible',
  'Both buffs active (doubled)': 'Les deux bonus actifs (doublés)',
  'Both skills building stacks': 'Les deux compétences génèrent des cumuls',
  'Counts as one piece of every brand and gear set you wear': 'Compte comme une pièce de chaque marque et ensemble d’équipement que vous portez',
  'Enemy within 15 m': 'Ennemi à moins de 15 m',
  'First bonus group active': 'Premier groupe de bonus actif',
  'Full bonus armor from the ability': 'Protection bonus maximale de la capacité',
  'Fully charged while scoped': 'Charge complète en visant à la lunette',
  'Headshot and body shot buffs active': 'Bonus de tir à la tête et de tir au corps actifs',
  'Headshot and headshot kill buffs active': 'Bonus de tir à la tête et d’élimination par tir à la tête actifs',
  'Hitting the highlighted body section': 'En touchant la zone du corps mise en évidence',
  'Hollow-point ammo loaded': 'Munitions à pointe creuse chargées',
  'In cover': 'À l’abri',
  'Into the Light stacks built in cover': 'Cumuls d’Into the Light accumulés à l’abri',
  'Long-term trophy buff': 'Bonus de trophée longue durée',
  'Near an ally or skill': 'Près d’un allié ou d’une compétence',
  'Near your deployed skills': 'Près de vos compétences déployées',
  'No skills deployed or on cooldown': 'Aucune compétence déployée ni en recharge',
  'Not taking damage': 'Sans subir de dégâts',
  'One of your skills is within 10 m': 'Une de vos compétences est à moins de 10 m',
  'Primed and swapped to': 'Amorcée puis prise en main',
  'Red debuff on the target': 'Malus rouge sur la cible',
  'Scales with your Status Effects bonus': 'Évolue avec votre bonus d’effets d’état',
  'Seeing Red active': 'Seeing Red actif',
  'Stacks spent on an enemy within 20 m': 'Cumuls dépensés sur un ennemi à moins de 20 m',
  'Target at 9 venom stacks': 'Cible à 9 cumuls de venin',
  'Target carries your mark': 'La cible porte votre marque',
  'Target has a status effect': 'La cible subit un effet d’état',
  'Target is 15 to 25 m away': 'La cible est à une distance de 15 à 25 m',
  'Target is 20 m away': 'La cible est à 20 m',
  'Target is bleeding': 'La cible saigne',
  'Target is blinded': 'La cible est aveuglée',
  'Target is burning': 'La cible brûle',
  'Target is confused': 'La cible est désorientée',
  'Target is ensnared': 'La cible est immobilisée',
  'Target is in the highest tier': 'La cible est au palier le plus haut',
  'Target is in the lowest tier': 'La cible est au palier le plus bas',
  'Target is not targeting you': 'La cible ne vous vise pas',
  'Target is not the marked enemy': 'La cible n’est pas l’ennemi marqué',
  'Target is pulsed': 'La cible est sous impulsion',
  'Target is shocked': 'La cible est sous choc électrique',
  'Target set on fire by your incinerator turret': 'Cible enflammée par votre tourelle incendiaire',
  'Target was hit by your shotgun or marksman rifle': 'La cible a été touchée par votre fusil à pompe ou votre fusil de précision',
  'While firing': 'Pendant le tir',
  'While firing continuously': 'Pendant un tir continu',
  'With bonus armor and enemies within 10 m': 'Avec de la protection bonus et des ennemis à moins de 10 m',

  // ---- seasonal calendar ----
  'Season': 'Saison',
  'Year 5 to today': 'De l’Année 5 à aujourd’hui',
  'Every event': 'Tous les événements',
  'All seasons': 'Toutes les saisons',
  'every event': 'tous les événements',
  'Season dates not recorded': 'Dates de saison non renseignées',
  'Next up': 'À venir',
  'just now': 'à l’instant',
  'No dated events were announced for this season.': 'Aucun événement daté n’a été annoncé pour cette saison.',
  'Active today': 'En cours aujourd’hui',
  'Upcoming events': 'Événements à venir',
  'Recently ended': 'Terminés récemment',
  'Dates partially documented': 'Dates partiellement connues',
  'Past events': 'Événements passés',
  'Past events and unlocks': 'Événements passés et déblocages',
  'Latest from Ubisoft': 'Dernières annonces d’Ubisoft',
  'Start': 'Début',
  '→ End': '→ Fin',
  'TBA': 'À confirmer',
  'Upcoming': 'À venir',
  'Until unlock': 'Avant le déblocage',
  'Until start': 'Avant le début',
  'Live now': 'En cours',
  'Until event end': 'Avant la fin',
  'Ended': 'Terminé',
  'Ended today': 'Terminé aujourd’hui',
  'Unlocked': 'Débloqué',
  'Unconfirmed': 'Non confirmé',
  'Dates TBA': 'Dates à confirmer',
  'End date unclear': 'Date de fin incertaine',
  'The calendar could not be loaded': 'Impossible de charger le calendrier',
  // event categories
  'Announced': 'Annoncé',
  'Classified Assignment': 'Mission classifiée',
  'Contest': 'Concours',
  'Event': 'Événement',
  'Event Pass': 'Passe d’événement',
  'Global Event': 'Événement mondial',
  'Incursion': 'Incursion',
  'Project Chain': 'Chaîne de projets',
  'Resource Bonus': 'Bonus de ressources',
  'Season Pass': 'Passe de saison',
  'Stat Bonus': 'Bonus de stats',
  'XP Bonus': 'Bonus d’XP',
  'PvE Dark Zone': 'Dark Zone JcE',
  'Seasonal Event': 'Événement saisonnier',
  // events written by hand (data/events.csv)
  'Shepherd XP bonus window': 'Période de bonus d’XP Berger',
  'End date not announced. Start date from a community calendar.': 'Date de fin non annoncée. Date de début issue d’un calendrier communautaire.',
  'New mission: missing JTF engineering team': 'Nouvelle mission : une équipe d’ingénieurs de la JTF portée disparue',
  'End date unconfirmed: 03 Nov per Ubisoft and 15 Oct per a community in-game report.': 'Date de fin non confirmée : le 3 nov. selon Ubisoft et le 15 oct. selon un relevé communautaire en jeu.',
  '2x Countdown Requisition': 'Réquisition de Compte à rebours x2',
  '5 caches': '5 caisses',
  'rewards from earlier campaigns': 'récompenses de campagnes précédentes',
  'Arm patches': 'Écussons',
  'caches': 'caisses',
  'weapon skin': 'apparence d’arme',
  'Break Overheal': 'Brisez le sursoin',
  'build Rage': 'accumulez de la Rage',
  'handling': 'maniement',
  'Returning projects': 'Projets de retour',
  'accelerated progression': 'progression accélérée',
  'The reported end date remains unclear.': 'La date de fin rapportée reste incertaine.',
  'Announced by Ubisoft': 'Annoncé par Ubisoft',
  'Start and end dates have not been announced.': 'Les dates de début et de fin n’ont pas été annoncées.',

  // ---- escalation ----
  'Escalation': 'Escalade',
  'Weekly rotation': 'Rotation hebdomadaire',
  'Target loot': 'Butin ciblé',
  "This week's Escalation missions, the loot each one targets today, and the Requisition vendor's daily caches.": 'Les missions d’Escalade de la semaine, le butin ciblé par chacune aujourd’hui et les caisses quotidiennes du vendeur de réquisition.',
  'Loot date': 'Date du butin',
  'Rotation week': 'Semaine de rotation',
  'Last updated': 'Dernière mise à jour',
  'Next reset': 'Prochaine réinitialisation',
  'Escalation missions': 'Missions d’Escalade',
  'Appearances': 'Apparitions',
  'Last seen': 'Dernière fois',
  'First time': 'Première fois',
  'Yesterday': 'Hier',
  'Escalation Requisition vendor': 'Vendeur de réquisition d’Escalade',
  'Daily caches': 'Caisses quotidiennes',
  'Prototype Gear Cache': 'Caisse d’équipement Prototype',
  'Prototype Weapon Cache': 'Caisse d’armes Prototype',
  'Prototype Random Cache': 'Caisse aléatoire Prototype',
  'Masks': 'Masques', 'Backpacks': 'Sacs à dos', 'Chest Pieces': 'Gilets', 'Body Armor': 'Gilets', 'Holsters': 'Holsters',
  'Assault Rifles': 'Fusils d’assaut', 'SMGs': 'Pistolets-mitrailleurs', 'LMGs': 'Fusils-mitrailleurs', 'Rifles': 'Fusils',
  'MMRs': 'Fusils de précision', 'Marksman Rifles': 'Fusils de précision', 'Shotguns': 'Fusils à pompe', 'Pistols': 'Pistolets',
  'Hyenas': 'Hyènes', 'Outcasts': 'Parias',
  'Chest talent': 'Talent de gilet',
  'Backpack talent': 'Talent de sac à dos',
  'Named items': 'Objets nommés',
  'Target loot details': 'Détails du butin ciblé',
  'The rotation could not be loaded': 'Impossible de charger la rotation',
  'The rotation could not be read.': 'La rotation est illisible.',
};

// Game stats, lower case. The French starts in lower case too; a capital is put back when
// the English had one.
export const TERMS = {
  'weapon damage': 'dégâts d’arme', 'all weapon damage': 'dégâts toutes armes', 'total weapon damage': 'dégâts d’arme totaux',
  'assault rifle damage': 'dégâts de fusil d’assaut', 'ar damage': 'dégâts de fusil d’assaut',
  'lmg damage': 'dégâts de fusil-mitrailleur', 'smg damage': 'dégâts de pistolet-mitrailleur',
  'shotgun damage': 'dégâts de fusil à pompe', 'rifle damage': 'dégâts de fusil',
  'marksman rifle damage': 'dégâts de fusil de précision', 'mmr damage': 'dégâts de fusil de précision',
  'pistol damage': 'dégâts de pistolet',
  'critical hit chance': 'chances de coup critique', 'critical chance': 'chances de coup critique',
  'critical hit damage': 'dégâts de coup critique', 'critical damage': 'dégâts de coup critique',
  'headshot damage': 'dégâts de tir à la tête',
  'damage to armor': 'dégâts à la protection', 'damage to health': 'dégâts à la santé',
  'damage to target out of cover': 'dégâts aux cibles hors abri', 'damage to targets out of cover': 'dégâts aux cibles hors abri',
  'rate of fire': 'cadence de tir', 'signature weapon damage': 'dégâts d’arme emblématique', 'melee damage': 'dégâts de corps à corps',
  'amplified damage': 'dégâts amplifiés', 'base damage': 'dégâts de base',
  'weapon handling': 'maniement de l’arme', 'accuracy': 'précision', 'weapon accuracy': 'précision de l’arme',
  'stability': 'stabilité', 'weapon stability': 'stabilité de l’arme', 'reload speed': 'vitesse de rechargement',
  'swap speed': 'vitesse de changement d’arme', 'optimal range': 'portée optimale',
  'magazine size': 'taille du chargeur', 'mag size': 'taille du chargeur', 'extra rounds': 'balles supplémentaires', 'rounds': 'balles',
  'ammo capacity': 'capacité de munitions',
  'armor': 'protection', 'total armor': 'protection totale', 'health': 'santé',
  'armor regeneration': 'régénération de protection', 'armor regen': 'régénération de protection',
  'armor on kill': 'protection par élimination', 'health on kill': 'santé par élimination',
  'explosive resistance': 'résistance aux explosifs', 'hazard protection': 'protection contre les risques',
  'protection from elites': 'protection contre les élites', 'incoming repairs': 'réparations reçues',
  'pulse resistance': 'résistance à l’impulsion', 'disrupt resistance': 'résistance aux perturbations',
  'status effect resistance': 'résistance aux effets d’état', 'shield health': 'santé du bouclier',
  'skill tier': 'rang de compétence', 'skill damage': 'dégâts de compétence', 'total skill damage': 'dégâts de compétence totaux',
  'skill haste': 'hâte de compétence', 'skill duration': 'durée de compétence',
  'repair skills': 'compétences de réparation', 'repair-skills': 'compétences de réparation', 'total skill repair': 'réparation de compétence totale',
  'status effects': 'effets d’état', 'status effect': 'effets d’état', 'skill health': 'santé de compétence',
  'skill efficiency': 'efficacité de compétence', 'explosive damage': 'dégâts explosifs',
  'burn damage': 'dégâts de brûlure', 'burn duration': 'durée de brûlure',
  'handling': 'maniement', 'reload': 'rechargement',
  'threat': 'menace', 'increased threat': 'menace accrue', 'reduced threat': 'menace réduite',
  // short forms on the item cards
  'armor regen.': 'régén. protection', 'expl. res.': 'rés. explosifs', 'hazard prot.': 'prot. risques',
  'inc. repairs': 'réparations reçues', 'skill dmg': 'dégâts comp.', 'haste': 'hâte', 'status': 'effets d’état',
  // skill details
  'active regeneration': 'régénération active', 'ally repair': 'réparation des alliés', 'ammo': 'munitions',
  'ammo cooldown': 'recharge des munitions', 'average damage': 'dégâts moyens', 'blast radius': 'rayon de l’explosion',
  'blast damage': 'dégâts de l’explosion', 'bleed damage': 'dégâts de saignement', 'bleed duration': 'durée de saignement',
  'blind duration': 'durée d’aveuglement', 'blind effect duration': 'durée d’aveuglement', 'bonus armor': 'protection bonus',
  'buff amount': 'valeur du bonus', 'buff angle': 'angle du bonus', 'buff duration': 'durée du bonus', 'buff range': 'portée du bonus',
  'buff strength': 'puissance du bonus', 'charges': 'charges', 'charging time': 'temps de charge',
  'cloud damage': 'dégâts du nuage', 'cloud duration': 'durée du nuage', 'cloud radius': 'rayon du nuage', 'cone angle': 'angle du cône',
  'conflict cooldown': 'recharge en Conflit', 'cooldown': 'temps de recharge', 'damage': 'dégâts', 'damage reduction': 'réduction des dégâts',
  'disorient duration': 'durée de désorientation', 'disrupt duration': 'durée de perturbation', 'duration': 'durée',
  'effect duration': 'durée de l’effet', 'emp blast radius': 'rayon de l’explosion IEM', 'emp effect duration': 'durée de l’effet IEM',
  'effect radius': 'rayon d’effet', 'ensnare duration': 'durée d’immobilisation', 'explosion damage': 'dégâts d’explosion',
  'explosion radius': 'rayon d’explosion', 'foam health': 'santé de la mousse', 'healing': 'soins',
  'holstered regeneration': 'régénération une fois rengainé', 'max targets': 'cibles max', 'number of bombs': 'nombre de bombes',
  'number of mines': 'nombre de mines', 'number of zones': 'nombre de zones', 'radius': 'rayon', 'range': 'portée',
  'refill speed': 'vitesse de réapprovisionnement', 'repair': 'réparation', 'armor repair': 'réparation de protection',
  'repair over time': 'réparation sur la durée', 'repair radius': 'rayon de réparation', 'revive armor': 'protection à la réanimation',
  'scan range': 'portée du scan', 'shock duration': 'durée du choc', 'shock radius': 'rayon du choc',
  'shock effect duration': 'durée de l’effet de choc', 'damage taken modifier': 'modificateur de dégâts subis',
  'skill refresh': 'réinitialisation de compétence', 'skill repair': 'réparation de compétence', 'speed': 'vitesse',
  'traps': 'pièges', 'zone': 'zone', 'zone duration': 'durée de la zone', 'zone health': 'santé de la zone',
};

export const SCOPED = [
  ['.ring-label span', { Gear: 'Équip.' }],
  ['.count-down i', { d: 'j' }],
];

const N = '[\\d.,\\u202f\\u00a0]+';
const rule = (source, make) => [new RegExp(`^${source}$`), make];
const s = n => (Number(n) > 1 ? 's' : '');

// m is the match, t translates a piece of it.
export const RULES = [
  // ---- build planner ----
  rule('named attribute, max (.+) estimated', m => `attribut nommé, max ${m[1]} (estimé)`),
  rule('max (.+?)(, estimated)?', m => `max ${m[1]}${m[2] ? ', estimé' : ''}`),
  rule('(.+) \\(estimated\\)', (m, t) => `${t(m[1])} (estimé)`),
  rule('older patch notes say (.+) at this level', m => `d’anciennes notes de mise à jour indiquent ${m[1]} à ce niveau`),
  rule('(.+) counted', m => `${m[1]} pris en compte`),
  rule('Assumes: (.+)\\.', (m, t) => `Hypothèse : ${t(m[1])}.`),
  rule(`(${N}) RPM`, m => `${m[1]} CPM`),
  rule(`(${N}) rounds`, m => `${m[1]} balles`),
  rule(`(${N}) damage`, m => `${m[1]} dégâts`),
  rule(`(${N})s reload`, m => `rechargement ${m[1]} s`),
  rule(`(${N})m range`, m => `portée ${m[1]} m`),
  rule(`(${N}[KM]?) dmg`, m => `${m[1]} dég.`),
  rule(`(${N}) mag`, m => `chargeur ${m[1]}`),
  rule('(\\d+) equipped', m => `${m[1]} équipée${s(m[1])}`),
  rule('(\\d+) pieces? equipped', m => `${m[1]} pièce${s(m[1])} équipée${s(m[1])}`),
  rule('(\\d+) pieces?', m => `${m[1]} pièce${s(m[1])}`),
  rule('Skill (\\d)', m => `Compétence ${m[1]}`),
  rule('(\\d+) of (\\d+) points', m => `${m[1]} sur ${m[2]} points`),
  rule('(\\d+) points', m => `${m[1]} point${s(m[1])}`),
  rule('(\\d+) added', m => `${m[1]} ajouté${s(m[1])}`),
  rule('(.+) \\(flat\\)', (m, t) => `${t(m[1])} (valeur fixe)`),
  rule('(.+) \\(/s\\)', (m, t) => `${t(m[1])} (/s)`),
  rule('(.+) %', (m, t) => `${t(m[1])} %`),
  rule('(.+) Signature weapon: (.+)\\.', (m, t) => `${t(m[1])} Arme emblématique : ${m[2]}.`),
  rule('\\+(\\d+)% weapon damage for (\\d+) weapon classes of your choice( \\(following your equipped weapons until you pick\\))?:',
    m => `+${m[1]}% de dégâts d’arme pour ${m[2]} catégories d’armes de votre choix${m[3] ? ' (suit vos armes équipées tant que vous n’avez pas choisi)' : ''} :`),
  rule('(\\d+) red', m => `${m[1]} rouge${s(m[1])}`),
  rule('(\\d+) blue', m => `${m[1]} bleu${s(m[1])}`),
  rule('(\\d+) yellow', m => `${m[1]} jaune${s(m[1])}`),
  rule('Cores: (\\d+) red / (\\d+) blue / (\\d+) yellow', m => `Attributs principaux : ${m[1]} rouge${s(m[1])} / ${m[2]} bleu${s(m[2])} / ${m[3]} jaune${s(m[3])}`),
  rule('(\\d+) conditional (?:talent is|talents are) not counted on the stat sheet\\.', m => (Number(m[1]) > 1
    ? `${m[1]} talents conditionnels ne sont pas pris en compte sur la fiche de stats.`
    : '1 talent conditionnel n’est pas pris en compte sur la fiche de stats.')),
  rule('Damage over (\\d+) seconds', m => `Dégâts sur ${m[1]} secondes`),
  rule('(.+) \\((.+) armor, (.+) health\\)', (m, t) => `${t(m[1])} (${m[2]} de protection, ${m[3]} de santé)`),
  rule('Skills at tier (\\d+)', m => `Compétences au rang ${m[1]}`),
  rule('(\\d+) exotic weapons equipped\\. The game allows one\\.', m => `${m[1]} armes exotiques équipées. Le jeu n’en autorise qu’une.`),
  rule('(\\d+) exotic gear pieces equipped\\. The game allows one\\.', m => `${m[1]} pièces d’équipement exotiques équipées. Le jeu n’en autorise qu’une.`),
  rule('(.+) watch: (\\d+) points spent, SHD level (\\d+) gives (\\d+)\\.', (m, t) => `Montre, catégorie ${t(m[1])} : ${m[2]} points dépensés, le niveau SHD ${m[3]} en donne ${m[4]}.`),
  rule(`(${N})% crit chance is above the (${N})% cap and does nothing\\.`, m => `${m[1]}% de chances de critique dépassent le plafond de ${m[2]}% et ne servent à rien.`),
  rule(`Skill tier (${N}) is above the cap of (\\d+)\\.`, m => `Le rang de compétence ${m[1]} dépasse le plafond de ${m[2]}.`),
  rule('(\\d+) empty slots?\\.', m => `${m[1]} emplacement${s(m[1])} vide${s(m[1])}.`),
  rule('(\\d+) attribute, mod or talent (?:choice is|choices are) still empty\\.', m => `${m[1]} choix d’attribut, de mod ou de talent encore vide${s(m[1])}.`),
  rule('Sustained DPS gained on (.+) from one more roll of each kind, at (\\d+)% headshots\\.',
    m => `DPS soutenu gagné sur ${m[1]} avec un attribut supplémentaire de chaque type, à ${m[2]}% de tirs à la tête.`),
  rule("Both builds use the view selected above \\((.+)\\) and each one's weapon in hand\\.",
    (m, t) => `Les deux builds utilisent la vue choisie ci-dessus (${t(m[1])}) et l’arme en main de chacun.`),
  rule('(.+) \\(core\\)', (m, t) => `${t(m[1])} (principal)`),
  rule('(.+) core', (m, t) => `Principal : ${t(m[1])}`),
  rule('Core: (.+)', (m, t) => `Attribut principal : ${t(m[1])}`),
  rule('Extra core: (.+)', (m, t) => `Attribut principal supplémentaire : ${t(m[1])}`),
  rule('Unique: (.+)', m => `Unique : ${m[1]}`),
  rule('Named perk: (.+)', m => `Avantage nommé : ${m[1]}`),
  rule('Not in the community sheet yet\\. Source: (.*?)\\.(?: (.+) copied from the standard (.+) until the real numbers are known\\.)?', m => {
    const words = { damage: 'dégâts', 'rate of fire': 'cadence de tir', magazine: 'chargeur', reload: 'rechargement' };
    const list = m[2] ? m[2].toLowerCase().split(', ').map(w => words[w] || w).join(', ') : '';
    return `Pas encore dans la feuille communautaire. Source : ${m[1]}.${list
      ? ` ${list.charAt(0).toUpperCase()}${list.slice(1)} repris du modèle standard ${m[3]} en attendant les vrais chiffres.` : ''}`;
  }),
  rule('(.+) Magazine Slot', m => `Emplacement de chargeur ${m[1]}`),
  rule('(.+) Muzzle Slot', m => `Emplacement de bouche ${m[1]}`),
  rule(`\\+(${N})% weapon damage each`, m => `+${m[1]}% de dégâts d’arme par grade`),
  rule(`\\+(${N})% on an armor core each`, m => `+${m[1]}% sur un attribut principal de protection par grade`),
  rule('Attribute (\\d)', m => `Attribut ${m[1]}`),
  rule('Mod slot (\\d)', m => `Emplacement de mod ${m[1]}`),
  rule('Works with the 4-piece bonus of (.+)\\.', m => `Fonctionne avec le bonus 4 pièces de ${m[1]}.`),
  rule('(.+) in total', m => `${m[1]} au total`),
  rule('sheet updated (.+)', m => `feuille mise à jour le ${m[1]}`),
  rule('Read from the community sheet\\. These tabs came from the bundled copy: (.+)\\.', m => `Lu depuis la feuille communautaire. Ces onglets viennent de la copie fournie : ${m[1]}.`),
  rule('A specialization boosts (\\d+) weapon classes\\. Remove one first\\.', m => `Une spécialisation renforce ${m[1]} catégories d’armes. Retirez-en une d’abord.`),
  rule('Saved "(.+)"\\.', m => `« ${m[1]} » enregistré.`),
  rule('Loaded "(.+)"\\.', m => `« ${m[1]} » chargé.`),
  [/^pvp (.+)$/i, (m, t) => `${t(m[1])} (JcJ)`],

  // ---- seasonal calendar ----
  rule('Year (\\d+)', m => `Année ${m[1]}`),
  rule('What is live, what is next and what has ended\\. (.+)\\.', (m, t) => `Ce qui est en cours, ce qui arrive et ce qui est terminé. ${t(m[1])}.`),
  rule('(\\d+) events on record since (.+)', m => `${m[1]} événements répertoriés depuis le ${m[2]}`),
  rule('(.+) → season end TBA', m => `${m[1]} → fin de saison à confirmer`),
  rule('(.+) → TBA', m => `${m[1]} → à confirmer`),
  rule('Calendar data updated (.+)', (m, t) => `Données du calendrier mises à jour ${t(m[1])}`),
  rule('checked (.+)', (m, t) => `vérifiées ${t(m[1])}`),
  rule('(\\d+) min ago', m => `il y a ${m[1]} min`),
  rule('(\\d+) h ago', m => `il y a ${m[1]} h`),
  rule('(\\d+) days? ago', m => `il y a ${m[1]} jour${s(m[1])}`),
  rule('Ended (\\d+) days? ago', m => `Terminé il y a ${m[1]} jour${s(m[1])}`),
  rule('(\\d+) entries', m => `${m[1]} entrées`),
  rule('(\\d+)% of the event has passed', m => `${m[1]}% de l’événement est écoulé`),
  rule('In-game reset is (\\d\\d:\\d\\d) UTC; countdowns use that daily boundary\\. Dates can change: entries with missing or conflicting dates are marked\\.',
    m => `La réinitialisation en jeu a lieu à ${m[1]} UTC ; les comptes à rebours s’appuient sur cette heure. Les dates peuvent changer : les entrées aux dates manquantes ou contradictoires sont signalées.`),

  // ---- escalation ----
  rule("Today's target loot has not been recorded yet\\. Showing (.+); the missions stay the same all week\\.",
    m => `Le butin ciblé du jour n’a pas encore été relevé. Affichage du ${m[1]} ; les missions restent les mêmes toute la semaine.`),
  rule('Show what (.+) gives', m => `Voir ce qu’apporte ${m[1]}`),
  rule('(\\d+) times?', m => `${m[1]} fois`),
  rule('Missions change every Tuesday and target loot every day at (\\d\\d:\\d\\d) UTC\\. Appearances are counted since (.+)\\. Select a target loot to see its bonuses\\. Confirm in game before spending tokens\\.',
    m => `Les missions changent chaque mardi et le butin ciblé chaque jour à ${m[1]} UTC. Les apparitions sont comptées depuis le ${m[2]}. Sélectionnez un butin ciblé pour voir ses bonus. Vérifiez en jeu avant de dépenser des jetons.`),
  rule('No details are on record for (.+)\\.', m => `Aucun détail enregistré pour ${m[1]}.`),

  // "6m (+20% Radius)": a skill's number with what the skill tier adds to it
  rule('(.+?) \\(([+\\-−].+)\\)', (m, t) => `${m[1]} (${t(m[2])})`),

  // ---- labels read out by screen readers; keep last ----
  rule('(.+) stacks', m => `Cumuls de ${m[1]}`),
  rule('(.+) value', (m, t) => `Valeur : ${t(m[1])}`),
  rule('(.+) level', (m, t) => `Niveau : ${t(m[1])}`),
];
